Add API Input Validation for simulation/ Endpoint
tum-v2/parloa-backend pull request #13
Opened 2023-11-16 15:27 UTC by vlknozr

- Added API input validation for the simulation/ endpoint with express-validator library
- Updated simulation data model

2023-11-17 15:38 UTC, ardaakcabuyuk requested changes
Thank you, Volkan :) Now, we have a solid basis for our validation logic 🚀

2023-11-18 14:54 UTC, weirdkey approved these changes

2023-11-19 13:50 UTC, ardaakcabuyuk approved these changes

2023-11-19 13:51 UTC, ardaakcabuyuk approved these changes

2023-11-19 13:52 UTC, ardaakcabuyuk submitted a review, later dismissed

2023-11-19 14:05 UTC, ardaakcabuyuk requested changes

2023-11-19 14:05 UTC, ardaakcabuyuk commented on src/simulation/api/simulation.controller.ts
> +    res.status(400).send({ error: error });
We shouldn't change these error codes, because all errors we'll have will not necessarily be failed validations (400). We might also have some server errors that should be sent as 500.

2023-11-19 14:05 UTC, ardaakcabuyuk commented on src/simulation/api/simulation.controller.ts
> +    res.status(400).send({ error: error });
We need an extra layer to differentiate between these kinds of errors. It should resolve to 400 when validation fails, and 500 for internal server errors.

2023-11-20 22:14 UTC, ardaakcabuyuk approved these changes

2023-11-20 22:27 UTC, merged