Add Jest support for simulation/ endpoint
tum-v2/parloa-backend pull request #15
Opened 2023-11-18 13:30 UTC by vlknozr

- Added test cases to validate the functionality of the simulation/ endpoint

2023-11-18 15:12 UTC, weirdkey commented
Nice job. Three tests are failing for me and it is due to the fixed ids for the simulation. What I would suggest is to use API from Arda for all simulations and for the actions later for updating, deleting, etc. just take the id of the first simulation. Except that it looks very good.

2023-11-18 15:30 UTC, vlknozr commented
That's a good idea. Thanks.

2023-11-18 16:05 UTC, weirdkey approved these changes

2023-11-19 14:07 UTC, ardaakcabuyuk requested changes
We should fix the failing test that prevents us from merging.

2023-11-19 14:56 UTC, weirdkey approved these changes

2023-11-20 18:08 UTC, ardaakcabuyuk approved these changes

2023-11-21 11:03 UTC, ardaakcabuyuk approved these changes

2023-11-21 11:03 UTC, merged