Feature/par 44 sim translate simulation script
tum-v2/parloa-backend pull request #24
Opened 2023-11-22 15:02 UTC by Mqqrc

Run conversation with flight booking mock api. Works with gpt-4. Json fixer is being finished in a new branch so gpt 3.5 is not completely working yet.

2023-11-22 19:26 UTC, weirdkey commented on src/simulation/db/models/simulation.model.ts
> +    serviceAgent: { type: Schema.Types.ObjectId, ref: 'Agent' },
Something that we need to consider is that when running A/B testing, then we would have two service agents. We could either handle it as an array or handle it as two objects. @ardaakcabuyuk should give his opinion on how to handle this.

2023-11-22 19:29 UTC, weirdkey commented
Fantastic job. Well done 👏 . One comment from my side except the one above. Can you remove the debug console logs which are comments?

2023-11-23 14:02 UTC, ardaakcabuyuk requested changes
Very good job guys, thank you a lot for your effort! I'm waiting for your comments 🚀

2023-11-23 14:04 UTC, ardaakcabuyuk reviewed
I'll resolve the conflicts, you don't need to worry about them.

2023-11-23 16:31 UTC, Mqqrc commented on src/simulation/db/models/simulation.model.ts
> +    serviceAgent: { type: Schema.Types.ObjectId, ref: 'Agent' },
Yeah exactly, we agree with Arda. But let's implement that later when it's needed.

2023-11-23 16:43 UTC, R0N222 commented on src/simulation/agents/custom.agent.ts
> +export class MsgHistoryItem {
Honestly not sure if it to much sense, as most of the things stored in the MsgHistoryItem are only used in very special cases. We can store the data far more efficient in the database, also it uses langchain components like the BaseMessage.
![image](https://github.com/tum-v2/parloa-backend/assets/73743893/ce934285-5d1d-4e8c-a585-1e68e0df5f7e)

Marc will take care of storing the message data efficiently in his flushing to database task.
Note MsgHistoryItem is also a class and not an interface like MessageDocument.

2023-11-23 16:50 UTC, Mqqrc commented on src/simulation/agents/custom.agent.ts
> +export class CustomAgent {
We should talk about that in a quick meeting, as this is also part of my current task. Have you got time tomorrow? Just suggest a time on slack.

2023-11-23 16:50 UTC, R0N222 commented on src/simulation/agents/custom.agent.ts
> +      if (action === MsgTypes.MSGTOUSER || action == 'message_to_user' || action == 'None') {
The AI always messes up to correctly print MSGTOUSER, and often prints 'message_to_user', so it is an easy way to fix a large chunk of formatting issues.

2023-11-23 18:06 UTC, weirdkey commented on src/simulation/agents/custom.agent.ts
> +      if (action === MsgTypes.MSGTOUSER || action == 'message_to_user' || action == 'None') {
I think it is part of the LLM basic styling conventions to handle it as in Python and it is OK to leave it that way

2023-11-24 13:40 UTC, ardaakcabuyuk approved these changes

2023-11-24 13:44 UTC, merged