Feature/par 154 eva basic implementation for sentiment analysis
tum-v2/parloa-backend pull request #52
Opened 2023-12-04 00:40 UTC by MarekLorenz

- add sentiment analysis, recovery rate and similarity metrics (all three metrics are implemented in this branch)
- add sigmoid normalization function
- Add Python handler to run Python scripts

2023-12-04 17:43 UTC, tcw0 requested changes

2023-12-04 17:43 UTC, tcw0 commented on src/evaluation/service/evaluation.similarity.py
> +                      for element in set(ngrams(message2.split(), n))]
Indentation error

2023-12-04 18:13 UTC, Fabi987 requested changes
Sorry for reviewing without being assigned haha, but I just wanted to try it out.
However, it unfortunately doesn't work with docker (see comment).
The implementation itself looks good, as far as I understand what you are doing there :sweat_smile:

2023-12-04 18:13 UTC, Fabi987 commented on src/evaluation/service/evaluation.python-wrapper.ts
> +}
When using docker, I get an internal server error:
`Command failed: python3 evaluation.recovery.py [...] /bin/sh: python3: not found\n`
I also checked it: python is indeed not installed in the docker container

Are you running the development server without docker?

2023-12-04 18:13 UTC, Fabi987 commented on src/evaluation/service/evaluation.python-wrapper.ts
> +}
What happens in the case of an error in the python script? Will the error message just silently be converted to a float? (Just a question, couldn't try it out). If yes, that should be changed in my opinion.

2023-12-16 07:37 UTC, Fabi987 requested changes

2023-12-16 07:37 UTC, Fabi987 commented on Dockerfile
>  EXPOSE 3000
I think you should keep the Dockerfile as it is, the meta team will be probably not very happy about changes (although you have just removed lines haha)

2023-12-16 21:24 UTC, Fabi987 approved these changes

2023-12-16 21:26 UTC, merged