Update Dockerfile to use Node:bullseye base image, add python functionality to Docker
tum-v2/parloa-backend pull request #88
Opened 2023-12-13 22:35 UTC by Ozanaydinn

Solves: https://linear.app/parloa-ws2324/issue/PAR-176/[meta]-hotfix-add-python-modules-for-evaluation

Base image changed from `Alpine `to `node:bullseye-slim`, which is based on Debian and therefore uses `glibc` so we don't have to install every single C dependency and finally can use pre-existing wheels.

It took nearly 25 mins to do everthing with Alpine, and with the current base image, when everything is cached (the python stuff, mainly) it took my computer 45 seconds to build the image, which is a decent time gain 🤯 Our image size is now 1.17 GB, and I think it was around 550MB with Alpine, so there is a tradeoff to be made here for sure. 

**Question for reviewers**

- Especially @amyjchao please try this and let me know if your scripts work, I have not tried to make them work. I only made sur that the code did not break.
- @ardaakcabuyuk Very simple fix for the conversation.service.ts.
- Also feel free to let me know if you know any base images that would be more suitable to our case, I would be grateful.

2023-12-13 22:37 UTC, ardaakcabuyuk approved these changes

2023-12-14 13:53 UTC, MarekLorenz requested changes

2023-12-14 13:53 UTC, MarekLorenz commented on Dockerfile
> +RUN pip3 install -r requirements.txt
The following command should be added here: 
`python3 -m spacy download en_core_web_sm`

This module is necessary for spacy to run. It can be united with the run command on line 24.

2023-12-14 14:06 UTC, MarekLorenz approved these changes
LGTM

2023-12-14 14:11 UTC, merged